### ISSUE TITLE
Intermittent install.sh download failure

### ISSUE THREAD

**Issue by mdial89f** [HatsuneMiku3939/direnv-action#120]
## Type of Issue:

- [x] Bug: Something isn't working

## What's broken?

Occasionally, maybe 1 build in 100 builds, the direnv-action fails during the curl step.
```
...

- name: Configure direnv
        uses: HatsuneMiku3939/direnv-action@v1
        
...

Command failed: curl -sfL https://direnv.net/install.sh | bash > /dev/null 2>&1
```

## What's the impact of this bug?

The job running the action fails.

## Steps to Reproduce?

Not sure!  We have this workflow running on a schedule across a few repositories, about once an hour. 

We've considered that maybe this is just a random network failure, or perhaps our girhub actions across our repos are making too many requests to direnv.net in too close of a timeframe, and maybe we're getting blocked.

Any help appreciated!

**Comment by HatsuneMiku3939** [comment]
@mdial89f 
I'm sorry for your inconvenience. I've been working on adding the feature to cache direnv binary and just finished it. A new feature will affect automatically on HatsuneMiku3939/direnv-action@v1

If new feature dose not resolve this issue, feel free to fork/PR. Any PR are welcome.
