### ISSUE TITLE
How do you prevent secrets from being divulged in the workflow?

### ISSUE THREAD

**Issue by kaihendry** [HatsuneMiku3939/direnv-action#235]
For example you can see my secret "kensentme" is printed https://github.com/kaihendry/dotSecretTest/actions/runs/6796471305/job/18476619647

![image](https://github.com/HatsuneMiku3939/direnv-action/assets/765871/21fe4c5b-808f-40ec-a656-b4151c50dafa)

**Comment by HatsuneMiku3939** [comment]
Hi @kaihendry,

Thank you for your feature request. I'm happy to announce that I've just merged a pull request that implements the masks feature. This new feature is now automatically available in HatsuneMiku3939/direnv-action@v1. You can use the 'masks' option to pass a comma-separated list of environment variable names you wish to mask.

Please check out the detailed example of the 'masks' option in the README.md for more information.

If this new feature doesn't fully address your issue, feel free to fork the project or submit a PR. All contributions are welcome!

Best regards,

@HatsuneMiku3939

**Comment by kaihendry** [comment]
Thank you! I think philosophically I will only rely on direnv for local overrides. I'd rather not checkin .envrc and rely on something like https://github.com/aws-actions/aws-secretsmanager-get-secrets instead after thinking about it.
